### ISSUE TITLE
Switch to High Performance Database

### ISSUE THREAD

**Issue by akayser2** [gobfink/Groceries#14]
We want a database that can support the ingestion of massive amounts of information. Cassandra seems like a good option for this task.

Initial success will look like being able to spin up a container running an instance of Cassandra.

**Comment by gobfink** [comment]
I think this might be OBE for now? we did compare the two sets of benchmarks and they looked pretty close for our current configuration

**Comment by kgustafson** [comment]
There were a couple of issues with performance.  I have addressed them.  I don't think the performance of the database is an issue now.  The issue was in the way that the data streams were being formed (looped structures that were configuring arrays and then passing the array) instead of just using the native queries within the database (which is super fast).  The other thing slowing down the grocery view was the sheer number of records being pushed to the browser.  Pagination helped this by only showing 25/50 (whatever) sub-set of data.  The system is much more efficient now.  I believe this issue should be closed as it is now OBE due to pagination and more efficient use of native sqlalchemy records.
